- type: job
  id: Stormtrooper
  name: forge-job-name-stormtrooper
  description: forge-job-desc-stormtrooper
  playTimeTracker: JobStormtrooper
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 1 # 48 hours
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 36000 # 10 hours
  startingGear: StormtrooperGear
  access:
  - SyndicateAgent
  - NuclearOperative
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconStormtrooper"
  supervisors: job-supervisors-syndicate
  weight: 40
  displayWeight: 40
  setPreference: true
  special:
  - !type:AddComponentSpecial
    components:
    - type: MailDisabled
    - type: SpecialSectorStationRecord
      recordGeneration: FalseRecord
    - type: NpcFactionMember
      factions:
      - NFSyndicate
  - !type:AddImplantSpecial
    implants: [ DeathRattleImplanter ]

- type: startingGear
  id: StormtrooperGear
  equipment:
    ears: ClothingHeadsetAltSyndicateShturm
    id: SyndiPDACStorm
    belt: ClothingBeltMilitaryWebbingSyndicateShturm
    mask: ClothingMaskGasSyndicate
    wallet: ClothingWalletLeatherSyndi
  storage:
    back:
    - NFBoxSurvivalExtended
    - SyndicateDataMinerFlatpack
    - ToolboxShturm

- type: chameleonOutfit
  id: StormtrooperChameleonOutfit
  job: Stormtrooper
