- type: startingGear
  id: SyndicateReinforcementSpySmugger
  parent: SyndicateOperativeClothing
  equipment:
    id: SyndiPDACadet
    ears: ClothingHeadsetAltSyndicateSmuggler
    gloves: ClothingHandsGlovesCombat
    jumpsuit: ClothingUniformJumpsuitRecruitSyndie
    head: ClothingHeadHatRedsoft
    pocket1: NFWeaponPistolViper
    wallet: ClothingWalletLeatherSyndi
  storage:
    back:
    - ToolboxKadet
