- type: department
  id: Frontier
  name: department-Frontier
  description: department-NF-description
  color: "#334E6D"
  weight: 50 # accounted for in jobs
  roles:
  - StationRepresentative
  - StationTrafficController
#  - Valet # nyano ## Forge-change
#  - NFJanitor # Forge-change
  - MailCarrier # nyano
  - SecurityGuard
  - OutpostMedic # Forge-add
  - OutpostEngineer # Forge-add
  - OutpostService # Forge-add

- type: department
  id: Antag
  name: department-Antag
  description: department-NFAntag-description
  color: "#DE3A3A"
  weight: -20 # accounted for in jobs
  roles:
  - NFPirateCaptain
  - NFPirateFirstMate
  - NFPirate
  - Prisoner #nyano
