# Base
- type: entity
  parent: SalvageHumanCorpse
  id: DungeonHumanCorpse
  suffix: Dead, Frontier
  save: false
  name: unidentified corpse
  description: I think they're dead.
  components:
  - type: StinkyTrait
  - type: NpcFactionMember
    factions:
    - SimpleHostile
  - type: Carriable # Carrying system from nyanotrasen.
  - type: Butcherable
    butcheringType: Spike
    spawned:
    - id: FoodMeatRotten
      amount: 5
  - type: TriggerOnBeingGibbed
  - type: GibOnTrigger
    deleteItems: true
    deleteOrgans: false # Forge-change: i think that not bad idea
    gib: false
    useArgumentEntity: true
